#include <iostream>
#include <string>
#include <iomanip>

/****************************************************************************************
Q: A program generated by connecting various components in a desired configuration is
called
A: a hardwired program.

Q: State one of the three concepts of the von Neumann architecture
A: data and instructions are both stored in a read/write memory; 
or the content of the memory is addressable by location regardless of the data type;
or executions occur sequentially unless explicitly modified.

Q: What is an interconnection structure?
A: An interconnection struction is a collection of paths connecting modules.

Q: What is a system bus?
A: A system bus is a bus the connects the main computer modules (processor/memory/I/O).
****************************************************************************************/

void MemoryIO(bool bus[],std::string memory[])
{
	int address = (int)(bus[3]) * 4 + (int)(bus[4]) * 2 + (int)(bus[5]);

	if(!bus[0] && bus[1] && bus[2]) 
	{
		std::string data = "";
		for(int i = 6;i < 9;i += 1)
		{
			data += (bus[i])?("1"):("0");
			bus[i-6] = true;
		}
		memory[address] = data;
	}
	else if(bus[0] && !bus[1] && bus[2])
	{
		for(int i = 6;i < 9;i += 1)
		{
			bus[i] = memory[address][i-6] == '1';
			bus[i-6] = true;
		}
	} 
}

void PrintBus(bool bus[])
{
	std::cout << std::setw(10) << "bus = {";

	for(int i = 0;i < 9;i += 1)
	{
		std::cout << bus[i];

		if(i != 8)
		{
			std::cout << ",";
		}
	}
	std::cout << "}\n";
}	

void PrintMemory(std::string memory[])
{
	std::cout << "memory = {";

	for(int i = 0;i < 8;i += 1)
	{
		std::cout << memory[i];

		if(i != 7)
		{
			std::cout << ",";
		}
	}
	std::cout << "}\n";
}	

int main()
{
	bool bus[9] = {true,false,true,false,true,true,true,true,false};
	std::string memory[8] = {"000","001","010","011","100","101","110","111"};
	std::cout << std::boolalpha;

	PrintBus(bus);
	PrintMemory(memory);
	MemoryIO(bus,memory);
	PrintBus(bus);
	PrintMemory(memory);

	return 0;
}
