def cartesian_product(A, B):
    result = []
    for i in range(0, len(A)):
        for j in range(0, len(B)):
            temp = []
            temp.append(A[i])
            temp.append(B[j])
            temp = tuple(temp)
            result.append(temp)
    return result

#These test lists are the sets (E x F) and G respectively
#the set (E x F) was also generated by this script

test1 = [(2, 1), (2, 5), (2, 7), (3, 1), (3, 5), (3, 7), (5, 1), (5, 5), (5, 7), (7, 1), (7, 5), (7, 7)]
test2 = [1,3,7,9,11,13,17,19]

#print(cartesian_product(test1,test2))
